[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gdex"
description = "Rule-based sentence scoring algorithm"
authors = [
    {name = "Ulf Hamster", email = "554c46@gmail.com"},
    {name = "Gregor Middell", email = "gregor.middell@bbaw.de"},
    {name = "Natalie Sürmeli", email = "natalie.suermeli@uni-potsdam.de"}
]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Education",
    "Topic :: Scientific/Engineering",
    "Topic :: Text Processing :: Linguistic"
]
requires-python = ">=3.7"
dependencies = ["spacy>=3.7"]
dynamic = ["readme", "version"]

[project.optional-dependencies]
dev = [
    "coverage",
    "flake8",
    "flake8-bugbear",
    "mypy",
    "pre-commit",
    "pytest",
    "de-core-news-sm @ https://github.com/explosion/spacy-models/releases/download/de_core_news_sm-3.7.0/de_core_news_sm-3.7.0-py3-none-any.whl#sha256=d88c737eb7eb766f730f6a2dcb99dfcdb81623e1e0d89a9c638a2182ac19c52e",
    "de_hdt_lg @ https://huggingface.co/zentrum-lexikographie/de_hdt_lg/resolve/main/de_hdt_lg-any-py3-none-any.whl#sha256=44bd0b0299865341ee1756efd60670fa148dbfd2a14d0c1d5ab99c61af08236a"
]

[project.urls]
Homepage = "https://github.com/zentrum-lexikographie/gdex"

[tool.coverage.run]
omit = ["tests/**/*.py"]

[tool.isort]
profile = "black"

[tool.setuptools.dynamic]
readme = {file = ["README.md"], content-type = "text/markdown"}
version = {attr = "gdex.version.__version__"}

[tool.setuptools.packages.find]
exclude = ["tests"]

[tool.setuptools.package-data]
"gdex" = ["de_whitelist.txt", "py.typed", "VulGer.csv"]
