name: Test

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        pip install -U pip setuptools wheel
        pip install '.[dev]'
    - name: Run unit tests
      run: |
        pytest
